/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'itemName' : string,
  'customerId' : Principal,
}
export type OrderStatus = { 'riderAssigned' : null } |
  { 'requested' : null } |
  { 'storeConfirmed' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export type PhoneNumber = string;
export interface Product {
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'productId' : bigint,
  'vendorId' : Principal,
  'image' : string,
  'price' : number,
}
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'phone' : PhoneNumber,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'store' : null } |
  { 'deliveryP' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, number, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createOrder' : ActorMethod<[string], bigint>,
  'createUserProfile' : ActorMethod<[PhoneNumber, string, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'generateOtp' : ActorMethod<[PhoneNumber], string>,
  'getAllCustomers' : ActorMethod<[], Array<UserProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllVendors' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStatus' : ActorMethod<[bigint], [] | [OrderStatus]>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getProductsByVendor' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isNewUser' : ActorMethod<[PhoneNumber], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string],
    undefined
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'verifyOtp' : ActorMethod<[PhoneNumber, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];