/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhoneNumber = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'store' : IDL.Null,
  'deliveryP' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'phone' : PhoneNumber,
});
export const OrderStatus = IDL.Variant({
  'riderAssigned' : IDL.Null,
  'requested' : IDL.Null,
  'storeConfirmed' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Int,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'itemName' : IDL.Text,
  'customerId' : IDL.Principal,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'productId' : IDL.Int,
  'vendorId' : IDL.Principal,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Int],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createOrder' : IDL.Func([IDL.Text], [IDL.Int], []),
  'createUserProfile' : IDL.Func([PhoneNumber, IDL.Text, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Int], [], []),
  'generateOtp' : IDL.Func([PhoneNumber], [IDL.Text], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getOrderById' : IDL.Func([IDL.Int], [IDL.Opt(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Int], [IDL.Opt(OrderStatus)], ['query']),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getProductsByVendor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isNewUser' : IDL.Func([PhoneNumber], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Int, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'verifyOtp' : IDL.Func([PhoneNumber, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhoneNumber = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'store' : IDL.Null,
    'deliveryP' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'phone' : PhoneNumber,
  });
  const OrderStatus = IDL.Variant({
    'riderAssigned' : IDL.Null,
    'requested' : IDL.Null,
    'storeConfirmed' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Int,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'itemName' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'productId' : IDL.Int,
    'vendorId' : IDL.Principal,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Int],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createOrder' : IDL.Func([IDL.Text], [IDL.Int], []),
    'createUserProfile' : IDL.Func([PhoneNumber, IDL.Text, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Int], [], []),
    'generateOtp' : IDL.Func([PhoneNumber], [IDL.Text], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllVendors' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getOrderById' : IDL.Func([IDL.Int], [IDL.Opt(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Int], [IDL.Opt(OrderStatus)], ['query']),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getProductsByVendor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isNewUser' : IDL.Func([PhoneNumber], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Int, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Int, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'verifyOtp' : IDL.Func([PhoneNumber, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };